# Generated by Django 4.2.1 on 2023-05-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_porcentaje_delete_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personales_exists', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('crediticias_exists', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('bancarias_exists', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('laborales_exists', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
            ],
        ),
    ]
