# Generated by Django 4.2.1 on 2023-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='bancarias_exists',
            field=models.BooleanField(choices=[(True, 'S'), (False, 'N')]),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='crediticias_exists',
            field=models.BooleanField(choices=[(True, 'S'), (False, 'N')]),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='laborales_exists',
            field=models.BooleanField(choices=[(True, 'S'), (False, 'N')]),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='personales_exists',
            field=models.BooleanField(choices=[(True, 'S'), (False, 'N')]),
        ),
    ]
