# Generated by Django 4.2.1 on 2023-05-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_referencia_bancarias_exists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
    ]
